# Customization from URL4IRL
# Expose ceres default network so that Coolify's Traefik instance can
# connect to SigNoz's frontend service and make it available under a
# secure subdomain of URL4IRL's domain.
networks:
  ceres_default:
    external: true

include:
  - test-app-docker-compose.yaml
  - docker-compose-minimal.yaml
